apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stock-app
  template:
    metadata:
      labels:
        app: stock-app
    spec:
      containers:
      - name: stock-container
        image: us-central1-docker.pkg.dev/grow-info-service/grow-repo/stock-app:6cf2ecfc1d3696da8f0f239cd1e147cc178b598f
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: stock-service
spec:
  type: LoadBalancer
  selector:
    app: stock-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080