name: Build and Push to Artifact Registry

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: grow-info-service
  GAR_LOCATION: us-central1
  REPOSITORY: grow-repo
  IMAGE: stock-app

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Google Auth
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Docker Auth
      run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

    - name: Build and Push
      run: |-
        docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}" .
        docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}"

    - name: Update K8s Manifest
      run: |-
        # ఇది k8s-deploy.yaml లో ఉన్న పాత ట్యాగ్‌ని కొత్త SHA తో మారుస్తుంది
        sed -i "s|image:.*|image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}|g" k8s-deploy.yaml
        
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"
        git add k8s-deploy.yaml
        git commit -m "🚀 Update image to ${{ github.sha }} [skip ci]"
        git push
